# Generated by Django 5.2.11 on 2026-03-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0008_rename_slots_available_opportunity_total_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
