# Generated by Django 5.2.11 on 2026-03-08 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0009_opportunity_is_active'),
        ('users', '0003_volunteerprofile_created_at_volunteerprofile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='organizers.opportunity')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_feedbacks', to='users.volunteerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['opportunity', '-created_at'], name='users_oppor_opportu_867137_idx')],
                'constraints': [models.UniqueConstraint(fields=('opportunity', 'volunteer'), name='unique_feedback_per_volunteer')],
            },
        ),
    ]
